Web/Controllers/OrderItemController.cs
using Application.Models;
using Microsoft.AspNetCore.Mvc;
using Web.Extensions;

namespace Web.Controllers
{
    public class OrderItemController : Controller
    {
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(OrderItemModel orderItemModel)
        {
            if (ModelState.IsValid)
            {
                var orderItems = TempData.Get<List<OrderItemModel>>("OrderItems") ?? new();
                orderItems.Add(orderItemModel);
                TempData.Set("OrderItems", orderItems);
                return RedirectToAction("Create", "Orders");
            }
            return View(orderItemModel);
        }
        public IActionResult Details(Guid id)
        {
            var orderItems = TempData.Peek<List<OrderItemModel>>("OrderItems");
            var orderItem = orderItems?.FirstOrDefault(x => x.Id == id);

            if (orderItem == null)
            {
                return NotFound();
            }
            return View(orderItem);
        }

        public IActionResult Edit(Guid id)
        {
            var orderItems = TempData.Peek<List<OrderItemModel>>("OrderItems") ?? new();
            var orderItem = orderItems.FirstOrDefault(item => item.Id == id);

            if (orderItem == null)
            {
                return NotFound();
            }

            return View(orderItem);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(Guid id, OrderItemModel orderItemModel)
        {
            if (ModelState.IsValid)
            {
                var orderItems = TempData.Get<List<OrderItemModel>>("OrderItems") ?? new();
                var orderItem = orderItems.FirstOrDefault(item => item.Id == id);
                var orderItemIndex = orderItems.IndexOf(orderItem);

                if (orderItem == null)
                {
                    return NotFound();
                }

                orderItems.Remove(orderItem);
                orderItems.Insert(orderItemIndex, orderItemModel);
                TempData.Set("OrderItems", orderItems);

                return RedirectToAction("Create", "Orders");
            }

            return View(orderItemModel);
        }

        public IActionResult Delete(Guid id)
        {
            var orderItems = TempData.Peek<List<OrderItemModel>>("OrderItems") ?? new();
            var orderItem = orderItems.FirstOrDefault(item => item.Id == id);

            if (orderItem == null)
            {
                return NotFound();
            }

            return View(orderItem);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public IActionResult DeleteConfirmed(Guid id)
        {
            var orderItems = TempData.Get<List<OrderItemModel>>("OrderItems") ?? new();
            var orderItem = orderItems.FirstOrDefault(item => item.Id == id);
            
            if (orderItem == null)
            {
                return NotFound();
            }
            
            orderItems.Remove(orderItem);
            TempData.Set("OrderItems", orderItems);

            return RedirectToAction("Create", "Orders");
        }
    }
}

Web/Views/OrderItem/Create.cshtml
@model Application.Models.OrderItemModel

<h2>Create Order Item</h2>

@using (Html.BeginForm("Create", "OrderItem", FormMethod.Post))
{
    <div class="form-horizontal">
        <h4>OrderItemModel</h4>
        <hr />
        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Quantity, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Quantity, new { htmlAttributes = new { @class = "form-control" } })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Unit, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Unit, new { htmlAttributes = new { @class = "form-control" } })

            </div>
        </div>
        <hr />
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Create", "Orders")
</div>

Web/Views/OrderItem/Delete.cshtml
@model Application.Models.OrderItemModel

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>OrderItem</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Quantity)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Quantity)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Unit)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Unit)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Create" asp-controller="Orders">Back to List</a>
    </form>
</div>

Web/Views/OrderItem/Details.cshtml
@model Application.Models.OrderItemModel

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>OrderItem</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Quantity)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Quantity)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Unit)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Unit)
        </dd>
    </dl>
    <a asp-action="Create" asp-controller="Orders">Back to List</a>
</div>

Web/Views/OrderItem/Edit.cshtml
@model Application.Models.OrderItemModel

<h2>Edit Order Item</h2>

@using (Html.BeginForm("Edit", "OrderItem", FormMethod.Post))
{
    <div class="form-horizontal">
        <h4>OrderItemModel</h4>
        <hr />
        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Quantity, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Quantity, new { htmlAttributes = new { @class = "form-control" } })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Unit, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Unit, new { htmlAttributes = new { @class = "form-control" } })

            </div>
        </div>
        <hr />
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Create", "Orders")
</div>